config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  patch 'questions/:id' => 'questions#update'
  get 'questions/:id/edit' => 'questions#edit', as:'edit_question'

  resources :questions
  root 'questions#new'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/question.rb
class Question < ApplicationRecord
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
    
  def index
      @questions = Question.all
    end
  
  
    def new
        @question = Question.new # @question のインスタンスを作成
      end
    
      
     def create
         question = Question.new(question_params)
          if question.save!
            redirect_to :action => "index"
          else
            redirect_to :action => "new"
          end
        end
      
      
     def show
         @question = Question.find(params[:id])
       end

       def edit
        @question = Question.find(params[:id])
      end

      def update
        question = Question.find(params[:id])
        if question.update(question_params)
          redirect_to :action => "show", :id => question.id
        else
          redirect_to :action => "new"
        end  
      end

      def destroy
        question = Question.find(params[:id])
        question.destroy
        redirect_to action: :index
      end

        private
        def question_params
          params.require(:question).permit(:title, :content, :image, :answer)
        end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Cookhelp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <header>
     <h1>おうちごはん相談室</h1>
     <div class="header-list">
     <ul>
       <li><%= link_to "ホーム", questions_path %></li>
       <li><%= link_to "投稿する",new_question_path %></li>
     </ul>
     </div>
   </header>
   <main>
     <%= yield %>
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

   </main>
   <footer>
      <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/questions/edit.html.erb
<%= form_for @question do |f| %>
     <div class="field">
    <%= f.label :お悩みへの回答  %>
    <%= f.text_area :answer, :size => "30x2" %>
     </div>
   
    <%= f.submit "このお悩みに回答する" %><br>
  <% end %>


 <%= link_to "投稿の詳細へ", question_path(@question) %><br>
 <%= link_to "一覧ページへ戻る", questions_path %>

app/views/questions/index.html.erb
<h1>ようこそ！おうちごはん相談室へ</h1>
<h3>一覧ぺージ</h3>

<div class="header-buttons">
  <div class="left">
    <%= link_to "新しく投稿する", new_question_path %>
  </div>

  <div class="right">
    <% unless user_signed_in? %>
      <%= link_to "ログイン", questions_path %>
      <%= link_to "新規登録", new_user_registration_path %>
    <% else %>
      <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <% end %>
  </div>
</div>


<div class="tweets-container">
  <% @questions.each do |q| %>
    <div class="tweet">
      <h2><%= q.title %></h2>

      <div class="content">
        <p><strong>質問:</strong> <%= q.content %></p>
      </div>

      
        <% if q.image.attached? %>
            <%= image_tag q.image, size: '250x200'%>
        <% end %>
     
      
      <div class="answer">
        <p><strong>回答:</strong> <%= q.answer %></p>
      </div>
      
      <%= link_to "投稿の詳細へ", question_path(q) %><br>
      <%= link_to "この投稿に回答する", edit_question_path(q), class: "answer-link" %><br>
      <%= button_to "削除する", question_path(q), method: :delete, data: { confirm: "本当に削除しますか？" } %>
      
    </div>
  <% end %>
</div>

app/views/questions/new.html.erb
<h1>ようこそ！おうちごはん相談室へ</h1>
<h3>自炊に関する悩みなど何でも投稿してね</h3>

<%= form_for @question do |f| %>
  <div class="field">
    <%= f.label :title, "質問タイトル" %>
    <%= f.text_field :title, size: 30, placeholder: "質問のタイトルを入力してください" %>
  </div>

  <div class="field">
    <%= f.label :content, "質問内容" %>
    <%= f.text_area :content, size: "30x5", placeholder: "質問の詳細内容を入力してください" %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :answer, "お悩みへの回答" %>
    <%= f.text_area :answer, size: "30x5", placeholder: "回答内容を入力してください" %>
  </div>

  <div class="actions">
    <%= f.submit "投稿する", class: "submit-button" %>
  </div>
<% end %>

<%= link_to "お悩み一覧に戻る", questions_path, class: "back-link" %>

app/views/questions/show.html.erb
<h1>ようこそ！おうちごはん相談室へ</h1>
<h3>質問詳細ページ</h3>

<div class="show question">
  <h2><strong>タイトル:</strong><%= @question.title %></h2>
  <p><strong>お悩み内容:</strong><%= @question.content %></p>
  
 
  <% if @question.image.attached? %> 
    <%= image_tag url_for(@question.image), size: "300x300" %> 
  <% end %>
   
  <p><strong>回答コメント:</strong><%= @question.answer %></p>
  <p><%= @question.created_at.strftime("%Y年%m月%d日 %H:%M") %></p>
</div>

<!-- 「このお悩みに回答する」リンクを回答の下に配置 -->
<%= link_to "このお悩みへの回答を追加", edit_question_path(@question) %>

<%= link_to "質問一覧に戻る", questions_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>